[package]
name = "implicit_ir"
version = "0.1.0"
authors = ["Noah Weninger <nweninge@ualberta.ca>"]
edition = "2018"

[dependencies]
ocl = "0.19"
image = "0.20"
hound = "3.4"
argparse = "0.2"
ron = "0.4"
serde= "1.0"
serde_derive = "1.0"
