#!/bin/bash
set -e

# shader cache is broken on nvidia
rm ~/.nv/ComputeCache -rf
message="// THIS FILE IS AUTOMATICALLY GENERATED BY run.sh. DO NOT EDIT"
echo $message > src/scene.cl
echo $message > src/scene_defines.h
echo $message > src/scene_config.ron

# move scene file into place
scene=$1
cat src/scenes/$1.cl >> src/scene.cl
shift

# generate scene config
sed -n -e '/^#define/p' src/scene.cl >> src/scene_defines.h
gcc src/gen_config.c -o gen_config
./gen_config >> src/scene_config.ron
rm gen_config

mkdir -p output
cargo run --release -- "$@"
